"""Flight model

Revision ID: 7c383c930c9c
Revises: 
Create Date: 2024-04-29 15:49:09.179994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c383c930c9c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flight",
        sa.Column("file_name", sa.String(length=120), nullable=False),
        sa.Column("fit", sa.Integer(), nullable=False),
        sa.Column("dep_date", sa.Date(), nullable=False),
        sa.Column("dep", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flight_id"), "flight", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flight_id"), table_name="flight")
    op.drop_table("flight")
    # ### end Alembic commands ###
